// MYSTORE
    export const CREATE_MY_STORE = 'CREATE_MY_STORE';
    export const GET_MY_STORE = 'GET_MY_STORE';
    export const GET_MY_STORE_SUCCESS = 'GET_MY_STORE_SUCCESS';
    export const UPDATE_MY_STORE = 'UPDATE_MY_STORE';
    export const UPDATE_MY_STORE_SUCCESS = 'UPDATE_MY_STORE_SUCCESS';
    export const DELETE_MY_STORE = 'DELETE_MY_STORE';
    export const MY_STORE_ERROR = 'MY_STORE_ERROR';
    // TEMPLATES
        export const ADD_MY_STORE_TEMPLATE = 'ADD_MY_STORE_TEMPLATE';
        export const ADD_MY_STORE_TEMPLATE_SUCCESS = 'ADD_MY_STORE_TEMPLATE_SUCCESS';
        export const SET_MY_STORE_TEMPLATE = 'SET_MY_STORE_TEMPLATE';
        export const SET_MY_STORE_TEMPLATE_SUCCESS = 'SET_MY_STORE_TEMPLATE_SUCCESS';
        export const MY_STORE_TEMPLATE_ERROR = 'MY_STORE_TEMPLATE_ERROR';

// STORE
    export const GET_STORE = 'GET_STORE';
    export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';
    export const STORE_ERROR = 'STORE_ERROR';

// STORE PRODUCTS
    // GET
        export const GET_STORE_PRODUCTS = 'GET_STORE_PRODUCTS';
        export const GET_STORE_PRODUCTS_SUCCESS = 'GET_STORE_PRODUCTS_SUCCESS';
        export const GET_STORE_PRODUCTS_ERROR = 'GET_STORE_PRODUCTS_ERROR';
        // CREATE
        export const CREATE_STORE_PRODUCT = 'CREATE_STORE_PRODUCT';
        export const CREATE_STORE_PRODUCT_SUCCESS = 'CREATE_STORE_PRODUCT_SUCCESS';
        export const CREATE_STORE_PRODUCT_ERROR = 'CREATE_STORE_PRODUCTS_ERROR';
        // UPDATE
        export const UPDATE_STORE_PRODUCT = 'UPDATE_STORE_PRODUCT';
        export const UPDATE_STORE_PRODUCT_SUCCESS = 'UPDATE_STORE_PRODUCT_SUCCESS';
        export const UPDATE_STORE_PRODUCT_ERROR = 'UPDATE_STORE_PRODUCTS_ERROR';
        // DELETE
        export const DELETE_STORE_PRODUCT = 'DELETE_STORE_PRODUCT';
        export const DELETE_STORE_PRODUCT_SUCCESS = 'DELETE_STORE_PRODUCT_SUCCESS';
        export const DELETE_STORE_PRODUCT_ERROR = 'DELETE_STORE_PRODUCTS_ERROR';

// STORE COLLECTIONS
    // GET
        export const GET_STORE_COLLECTIONS = 'GET_STORE_COLLECTIONS';
        export const GET_STORE_COLLECTIONS_SUCCESS = 'GET_STORE_COLLECTIONS_SUCCESS';
        export const GET_STORE_COLLECTIONS_ERROR = 'GET_STORE_COLLECTIONS_ERROR';
        // CREATE
        export const CREATE_STORE_COLLECTION = 'CREATE_STORE_COLLECTION';
        export const CREATE_STORE_COLLECTION_SUCCESS = 'CREATE_STORE_COLLECTION_SUCCESS';
        export const CREATE_STORE_COLLECTION_ERROR = 'CREATE_STORE_COLLECTIONS_ERROR';
        // UPDATE
        export const UPDATE_STORE_COLLECTION = 'UPDATE_STORE_COLLECTION';
        export const UPDATE_STORE_COLLECTION_SUCCESS = 'UPDATE_STORE_COLLECTION_SUCCESS';
        export const UPDATE_STORE_COLLECTION_ERROR = 'UPDATE_STORE_COLLECTIONS_ERROR';
        // DELETE
        export const DELETE_STORE_COLLECTION = 'DELETE_STORE_COLLECTION';
        export const DELETE_STORE_COLLECTION_SUCCESS = 'DELETE_STORE_COLLECTION_SUCCESS';
        export const DELETE_STORE_COLLECTION_ERROR = 'DELETE_STORE_COLLECTIONS_ERROR';

// AUTH
    export const GET_AUTH = 'GET_AUTH';
    export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
    export const SET_AUTH = 'SET_AUTH';
    export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';
    export const UPDATE_AUTH = 'UPDATE_AUTH';
    export const UPDATE_AUTH_SUCCESS = 'UPDATE_AUTH_SUCCESS';
    export const DELETE_AUTH = 'DELETE_AUTH';
    export const AUTH_ERROR = 'AUTH_ERROR';
// LOGOUT
    export const LOGOUT = 'LOGOUT';